name: lightbug
description: Work with Lightbug protocols and devices
dependencies:
  coordinate:
    url: github.com/lightbug-io/toit-coordinate
    version: ^1.0.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.8.1
  watchdog:
    url: github.com/toitware/toit-watchdog
    version: ^1.4.1
