name: Tests

on:
    push:
    pull_request:
        branches:
            - 'main'
        
jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v5

        - uses: toitlang/action-setup@v1
          with:
            toit-version: 'v2.0.0-alpha.150'

        - run: make test
